//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace iExchange.StateServer.TradingConsole
{
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.ComponentModel;
	using System.Web.Services;

	using iExchange.Common;

	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "Service2Soap", Namespace = "http://www.omnicare.com/TradingConsole/")]
	public class Service2 : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		/// <remarks/>
		public Service2()
		{
			this.Url = "http://192.168.1.107/iExchange/TradingConsole/Service2.asmx";
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/TradingConsole/HelloWorld", RequestNamespace = "http://www.omnicare.com/TradingConsole/", ResponseNamespace = "http://www.omnicare.com/TradingConsole/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string HelloWorld()
		{
			object[] results = this.Invoke("HelloWorld", new object[0]);
			return ((string)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public string EndHelloWorld(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/TradingConsole/UnRegister", RequestNamespace = "http://www.omnicare.com/TradingConsole/", ResponseNamespace = "http://www.omnicare.com/TradingConsole/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void UnRegister(Token token)
		{
			this.Invoke("UnRegister", new object[] {
													   token});
		}

		/// <remarks/>
		public System.IAsyncResult BeginUnRegister(Token token, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("UnRegister", new object[] {
																   token}, callback, asyncState);
		}

		/// <remarks/>
		public void EndUnRegister(System.IAsyncResult asyncResult)
		{
			this.EndInvoke(asyncResult);
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/TradingConsole/AddCommand", RequestNamespace = "http://www.omnicare.com/TradingConsole/", ResponseNamespace = "http://www.omnicare.com/TradingConsole/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void AddCommand(Token token, Command command)
		{
			this.Invoke("AddCommand", new object[] {
													   token,
													   command});
		}

		/// <remarks/>
		public System.IAsyncResult BeginAddCommand(Token token, Command command, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("AddCommand", new object[] {
																   token,
																   command}, callback, asyncState);
		}

		/// <remarks/>
		public void EndAddCommand(System.IAsyncResult asyncResult)
		{
			this.EndInvoke(asyncResult);
		}

/////////


        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/TradingConsole/KickoutPredecessor", RequestNamespace = "http://www.omnicare.com/TradingConsole/", ResponseNamespace = "http://www.omnicare.com/TradingConsole/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void KickoutPredecessor(Guid userId)
        {
            this.Invoke("KickoutPredecessor", new object[] { userId });
        }

        /// <remarks/>
        public System.IAsyncResult BeginKickoutPredecessor(Guid userId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("KickoutPredecessor", new object[] {userId}, callback, asyncState);
        }

        /// <remarks/>
        public void EndKickoutPredecessor(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

/////////

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/TradingConsole/UpdateLoginState", RequestNamespace = "http://www.omnicare.com/TradingConsole/", ResponseNamespace = "http://www.omnicare.com/TradingConsole/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void UpdateLoginState(Token token, bool isLogin)
		{
			this.Invoke("UpdateLoginState", new object[] {
															 token,
															 isLogin});
		}

		/// <remarks/>
		public System.IAsyncResult BeginUpdateLoginState(Token token, bool isLogin, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("UpdateLoginState", new object[] {
																		 token,
																		 isLogin}, callback, asyncState);
		}

		/// <remarks/>
		public void EndUpdateLoginState(System.IAsyncResult asyncResult)
		{
			this.EndInvoke(asyncResult);
		}
	}
}
