//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//  
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace iExchange.StateServer.FileExchangeServer
{
	using System.Diagnostics;
	using System.Web.Services;
	using System.ComponentModel;
	using System.Web.Services.Protocols;
	using System;
	using System.Xml.Serialization;


	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://www.omnicare.com/FileExchangeServer/")]
	public class Service : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		/// <remarks/>
		public Service()
		{
			string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["FileExchangeServer.Service"];
			if ((urlSetting != null))
			{
				this.Url = string.Concat(urlSetting, "");
			}
			else
			{
				this.Url = "http://ws0203/iExchange%20Team/iExchange.V3/FileExchangeServer/Service.asmx";
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/FileExchangeServer/HelloWorld", RequestNamespace = "http://www.omnicare.com/FileExchangeServer/", ResponseNamespace = "http://www.omnicare.com/FileExchangeServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string HelloWorld()
		{
			object[] results = this.Invoke("HelloWorld", new object[0]);
			return ((string)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public string EndHelloWorld(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/FileExchangeServer/Start", RequestNamespace = "http://www.omnicare.com/FileExchangeServer/", ResponseNamespace = "http://www.omnicare.com/FileExchangeServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool Start()
		{
			object[] results = this.Invoke("Start", new object[0]);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginStart(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Start", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public bool EndStart(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/FileExchangeServer/Stop", RequestNamespace = "http://www.omnicare.com/FileExchangeServer/", ResponseNamespace = "http://www.omnicare.com/FileExchangeServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool Stop()
		{
			object[] results = this.Invoke("Stop", new object[0]);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginStop(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Stop", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public bool EndStop(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/FileExchangeServer/MoneyFile", RequestNamespace = "http://www.omnicare.com/FileExchangeServer/", ResponseNamespace = "http://www.omnicare.com/FileExchangeServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool MoneyFile(string loginId, string password, System.DateTime fromTradeDay, System.DateTime toTradeDay, string customerIdentifier)
		{
			object[] results = this.Invoke("MoneyFile", new object[] {
                        loginId,
                        password,
                        fromTradeDay,
                        toTradeDay,
                        customerIdentifier});
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginMoneyFile(string loginId, string password, System.DateTime fromTradeDay, System.DateTime toTradeDay, string customerIdentifier, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("MoneyFile", new object[] {
                        loginId,
                        password,
                        fromTradeDay,
                        toTradeDay,
                        customerIdentifier}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndMoneyFile(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/FileExchangeServer/DailyReport", RequestNamespace = "http://www.omnicare.com/FileExchangeServer/", ResponseNamespace = "http://www.omnicare.com/FileExchangeServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool DailyReport(string loginId, string password, System.DateTime tradeDay, string customerIdentifier)
		{
			object[] results = this.Invoke("DailyReport", new object[] {
                        loginId,
                        password,
                        tradeDay,
                        customerIdentifier});
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginDailyReport(string loginId, string password, System.DateTime tradeDay, string customerIdentifier, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("DailyReport", new object[] {
                        loginId,
                        password,
                        tradeDay,
                        customerIdentifier}, callback, asyncState);
		}

		/// <remarks/>
		public bool EndDailyReport(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}
	}
}
