//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iExchange.StateServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder2.asmx")]
        public string iExchange_StateServer_DealingConsole_Service_PlaceHolder2 {
            get {
                return ((string)(this["iExchange_StateServer_DealingConsole_Service_PlaceHolder2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder3.asmx")]
        public string iExchange_StateServer_FileExchangeServer_Service_PlaceHolder3 {
            get {
                return ((string)(this["iExchange_StateServer_FileExchangeServer_Service_PlaceHolder3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder4.asmx")]
        public string iExchange_StateServer_PolamediaServer_Service_PlaceHolder4 {
            get {
                return ((string)(this["iExchange_StateServer_PolamediaServer_Service_PlaceHolder4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder6.asmx")]
        public string iExchange_StateServer_RiskMonitor_Service_PlaceHolder6 {
            get {
                return ((string)(this["iExchange_StateServer_RiskMonitor_Service_PlaceHolder6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder7.asmx")]
        public string iExchange_StateServer_TradingConsole_Service_PlaceHolder7 {
            get {
                return ((string)(this["iExchange_StateServer_TradingConsole_Service_PlaceHolder7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder8.asmx")]
        public string iExchange_StateServer_TradingMonitor_Service_PlaceHolder8 {
            get {
                return ((string)(this["iExchange_StateServer_TradingMonitor_Service_PlaceHolder8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder11.asmx")]
        public string iExchange_StateServer_QuotationCollector_Service_PlaceHolder11 {
            get {
                return ((string)(this["iExchange_StateServer_QuotationCollector_Service_PlaceHolder11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder.asmx")]
        public string iExchange_StateServer_QuotationCollector_Authentication_Service1 {
            get {
                return ((string)(this["iExchange_StateServer_QuotationCollector_Authentication_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/Temp%20Team/ExchangeMapping/ExchangeSwitch/iExchangeToiExchange/" +
            "iExchangeMappingService.asmx")]
        public string iExchange_StateServer_ExchangeMapping_iExchangeMappingService {
            get {
                return ((string)(this["iExchange_StateServer_ExchangeMapping_iExchangeMappingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws0301/iExchangeCollection/iExchange3%20Team/iExchange3/TransactionServer/" +
            "Service.asmx")]
        public string iExchange_StateServer_TransactionServer_Service_Service {
            get {
                return ((string)(this["iExchange_StateServer_TransactionServer_Service_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder5.asmx")]
        public string iExchange_StateServer_QuotationServer_Service_PlaceHolder5 {
            get {
                return ((string)(this["iExchange_StateServer_QuotationServer_Service_PlaceHolder5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/iExchange%20Team/Test/PlaceHolder/PlaceHolder9.asmx")]
        public string iExchange_StateServer_TransactionServer_Service_PlaceHolder9 {
            get {
                return ((string)(this["iExchange_StateServer_TransactionServer_Service_PlaceHolder9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws0308/iExchange/FaxAndEmailService/FaxEmailService.asmx")]
        public string iExchange_StateServer_FaxEmail_FaxEmailService {
            get {
                return ((string)(this["iExchange_StateServer_FaxEmail_FaxEmailService"]));
            }
        }
    }
}
