
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace iExchange.StateServer.PolamediaServer
{
	using System.Diagnostics;
	using System.Web.Services;
	using System.ComponentModel;
	using System.Web.Services.Protocols;
	using System;
	using System.Xml.Serialization;


	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "AuthenticationSoap", Namespace = "http://www.omnicare.com/PolamediaServer/")]
	public class Authentication : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		/// <remarks/>
		public Authentication()
		{
			string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["PolamediaServer.Authentication"];
			if ((urlSetting != null))
			{
				this.Url = string.Concat(urlSetting, "");
			}
			else
			{
				this.Url = "http://localhost/iExchange%20Team/iExchange.V3/PolamediaServer/Authentication.asmx";
			}
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/PolamediaServer/HelloWorld", RequestNamespace = "http://www.omnicare.com/PolamediaServer/", ResponseNamespace = "http://www.omnicare.com/PolamediaServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string HelloWorld()
		{
			object[] results = this.Invoke("HelloWorld", new object[0]);
			return ((string)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public string EndHelloWorld(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/PolamediaServer/Start", RequestNamespace = "http://www.omnicare.com/PolamediaServer/", ResponseNamespace = "http://www.omnicare.com/PolamediaServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool Start()
		{
			object[] results = this.Invoke("Start", new object[0]);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginStart(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Start", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public bool EndStart(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/PolamediaServer/Stop", RequestNamespace = "http://www.omnicare.com/PolamediaServer/", ResponseNamespace = "http://www.omnicare.com/PolamediaServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public void Stop()
		{
			this.Invoke("Stop", new object[0]);
		}

		/// <remarks/>
		public System.IAsyncResult BeginStop(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("Stop", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public void EndStop(System.IAsyncResult asyncResult)
		{
			this.EndInvoke(asyncResult);
		}

		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnicare.com/PolamediaServer/GetLoginStatus", RequestNamespace = "http://www.omnicare.com/PolamediaServer/", ResponseNamespace = "http://www.omnicare.com/PolamediaServer/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public bool GetLoginStatus()
		{
			object[] results = this.Invoke("GetLoginStatus", new object[0]);
			return ((bool)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult BeginGetLoginStatus(System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("GetLoginStatus", new object[0], callback, asyncState);
		}

		/// <remarks/>
		public bool EndGetLoginStatus(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((bool)(results[0]));
		}
	}
}
